class Characters:
    def __init__(self, name: str, typing: str, gender: str, allies: str, side: str, dmg_main: str, dmg_elem, abilities: list, pos: list = [], leadappliesto: list = [], leadgives: list = [[]], suppappliesto: list = [], suppgives: list = [[]]):
        self.name = name
        self.typing = typing
        self.gender = gender
        self.allies = allies
        self.side = side
        self.dmg_main = dmg_main
        self.dmg_elem = dmg_elem
        self.abilities = abilities
        self.pos = pos
        self.leadappliesto = leadappliesto
        self.leadgives = leadgives
        self.suppappliesto = suppappliesto
        self.suppgives = suppgives

#DO UNIFORMS (eventually)
#Adjust Thor's code to include the leadership if they have the artifact
#is Kahhori a support?
Odin = Characters("Odin", "universal", "male", "alien", "hero", "energy", "lightning", ["command", "energy projection"], ["leader"], ["all allies"], [["lightning", "debuff cleanse"]])
Enchantress = Characters("Enchantress", "blast", "female", "alien", "villain", "energy", "mind", ["magic", "mind"], ["leader", "support"], ["all allies"], [["debuff effect increase"]], ["all allies", "villain"], [["mind", "mind resist"], ["all attack", "damage to boss"]])
Malekith = Characters("Malekith", "blast", "male", "alien", "villain", "energy", "none", ["pure evil", "symbiote"], ["leader"], ["all allies"], [["debuff cleanse"]])
Ulik = Characters("Ulik", "combat", "male", "alien", "villain", "physical", "none", ["strong", "durability"], ["leader"], ["all allies"], [["physical"]])
Angela = Characters("Angela", "universal", "female", "alien", "hero", "physical", "none", ["weapons master"], ["support"], [], [[]], ["hero"], [["villain"]])
AdamWarlock = Characters("Adam Warlock", "blast", "male", "creature", "hero", "energy", "none", ["magic", "time freezing immunity"])
AntMan = Characters("Ant-Man", "speed", "male", "human", "hero", "physical", "none", ["agility"])
BlackBolt = Characters("Black Bolt", "universal", "male", "inhuman", "hero", "energy", "none", ["fast movement", "energy projection"], ["leader"], ["inhuman"], [["all attack"]])
BlackWidow = Characters("Black Widow", "speed", "female", "human", "hero", "physical", "none", ["agility", "agent"])
BlueDragon = Characters("Blue Dragon", "blast", "female", "human", "hero", "energy", "lightning", ["warriors of the sky", "leadership", "shock"], ["leader"], ["warriors of the sky"], [["all attack", "debuff cleanse"]])
CaptainAmerica = Characters("Captain America", "combat", "male", "human", "villain", "physical", "none", ["leadership", "command", "zombie"], ["leader"], ["all allies"], [["hp"]])
SharonRogers = Characters("Captain America (Sharon Rogers)", "blast", "female", "human", "hero", "energy", "none", ["leadership", "energy projection"])
Carnage = Characters("Carnage", "combat", "male", "human", "villain", "physical", "none", ["pure evil", "healing", "symbiote"], ["leader"], ["symbiote"], [["debuff cleanse", "all defense"]])
DoctorOctopus = Characters("Doctor Octopus", "combat", "male", "human", "villain", "physical", "none", ["machine", "durability", "sinister six"], ["leader"], ["all allies"], [["hp"]])
Gamora = Characters("Gamora", "speed", "female", "alien", "hero", "physical", "none", ["agility", "weapons master", "guardians of the galaxy"], ["leader"], ["speed"], [["physical"]])
Hulk = Characters("Hulk", "combat", "male", "human", "villain", "hp", "none", ["gamma radiation", "durability"])
Kang = Characters("Kang The Conqueror", "universal", "male", "human", "villain", "energy", "none", ["pure evil", "fast movement"], ["leader"], ["Kang", "all allies"], [["all attack"], ["debuff cleanse"]])
LunaSnow = Characters("Luna Snow", "speed", "female", "human", "hero", "energy", "cold", ["leadership", "cold blooded"])
Mysterio = Characters("Mysterio", "blast", "male", "human", "villain", "energy", "mind", ["mind", "sinister six"], ["support"], [], [[]], ["villain"], [["damage to boss", "all attack"]])
IronMan = Characters("Iron Man", "blast", "male", "human", "hero", "energy", "none", ["machine", "energy projection"])
JeanGrey = Characters("Jean Grey", "universal", "female", "mutant", "villain", "energy", "fire", ["mind", "mind resist", "phoenix force"], ["leader"], ["all allies"], [["debuff cleanse"]])
Magneto = Characters("Magneto", "blast", "male", "mutant", "villain", "energy", "none", ["energy projection", "mind resist"], ["leader"], ["mutant"], [["all attack"]])
MoonKnight = Characters("Moon Knight", "combat", "male", "human", "hero", "physical", "none", ["weapons master", "leadership"])
Namor = Characters("Namor", "combat", "male", "mutant", "villain", "physical", "cold", ["strong", "durability"])
ProfessorX = Characters("Professor X", "blast", "male", "mutant", "hero", "energy", "mind", ["leadership", "mind", "mind resist"], ["leader"], ["mutant"], [["all attack", "mind resist"]])
ShadowShell = Characters("Shadow Shell", "speed", "female", "human", "hero", "physical", "poison", ["warriors of the sky", "agility", "poison"], ["support"], [], [[]], ["warriors of the sky"], [["all defense", "dr"]])
SpiderGwen = Characters("Spider-Gwen", "speed", "female", "human", "hero", "physical", "none", ["spider-sense", "agility", "leadership"])
SpiderMan = Characters("Spider-Man", "speed", "male", "human", "hero", "physical", "none", ["spider-sense", "agility", "leadership"])
MilesMorales = Characters("Spider-Man (Miles Morales)", "speed", "male", "human", "hero", "physical", "lightning", ["spider-sense", "agility", "leadership"], ["leader"], ["Spider-Man (Miles Morales)"], [["all attack"]])
StarLord = Characters("Star-Lord", "blast", "male", "alien", "hero", "energy", "none", ["weapons master", "command", "guardians of the galaxy"], ["leader"], ["blast"], [["energy"]])
Storm = Characters("Storm", "blast", "female", "mutant", "hero", "energy", "lightning", ["shock", "command"], ["support"], [], [[]], ["all allies"], [["ignore dodge", "all elem"]])
Thanos = Characters("Thanos", "universal", "male", "alien", "villain", "physical", "none", ["power cosmic", "durability", "pure evil"], ["leader"], ["villain"], [["all attack", "all defense", "debuff cleanse"]])
Thor = Characters("Thor", "universal", "male", "alien", "hero", "energy", "lightning", ["shock", "leadership"])
Venom = Characters("Venom", "combat", "male", "human", "hero", "physical", "none", ["healing", "symbiote"], ["support"], [], [[]], ["all allies"], [["crit damage"]])
Wolverine = Characters("Wolverine", "combat", "male", "mutant", "hero", "physical", "none", ["weapons master", "healing"])
Sylvie = Characters("Sylvie", "universal", "female", "alien", "hero", "energy", "none", ["mind", "chill"])
CaptainMarvel = Characters("Captain Marvel", "universal", "female", "human", "hero", "energy", "none", ["fast movement", "leadership", "energy projection"], ["leader"], ["all allies"], [["energy"]])
Loki = Characters("Loki", "universal", "male", "alien", "villain", "energy", "none", ["mind", "chill"])
NickFury = Characters("Nick Fury", "speed", "male", "human", "hero", "physical", "none", ["agent", "leadership", "weapons master"], ["leader", "support"], ["hero"], [["all attack"]], ["hero"], [["super armor", "all defense", "incapacitation immunity", "villain"]])
Korath = Characters("Korath", "speed", "male", "alien", "villain", "physical", "none", ["weapons master", "pure evil"])
MinnErva = Characters("Minn-Erva", "combat", "female", "alien", "villain", "physical", "none", ["strong", "agility", "pure evil"])
MsMarvel = Characters("Ms. Marvel (Kamala Khan)", "speed", "female", "human", "hero", "physical", "none", ["strong", "leadership"])
Spectrum = Characters("Spectrum", "blast", "female", "human", "hero", "energy", "none", ["leadership", "energy projection"], ["leader"], ["all allies"], [["energy", "ignore dodge"]])
BlackPanther = Characters("Black Panther", "combat", "male", "human", "hero", "physical", "none", ["agility", "command"], ["leader"], ["all allies"], [["crit rate"]])
Cable = Characters("Cable", "blast", "male", "mutant", "hero", "energy", "none", ["weapons master", "leadership", "machine"], ["leader"], ["all allies"], [["ignore dodge"]])
DoctorStrange = Characters("Doctor Strange", "blast", "male", "human", "villain", "energy", "none", ["magic", "fast movement", "zombie"], ["leader"], ["all allies"], [["energy", "ignore dodge"]])
GhostRider = Characters("Ghost Rider", "universal", "male", "human", "hero", "energy", "fire", ["leadership", "flame"])
AncientOne = Characters("Ancient One", "blast", "female", "human", "hero", "energy", "none", ["magic", "leadership"], ["leader", "support"], ["blast"], [["energy"]], ["all allies"], [["all resist", "ignore dodge", "all elem"]])
Apocalypse = Characters("Apocalypse", "combat", "male", "mutant", "villain", "energy", "mind", ["fast movement", "pure evil", "durability"], ["leader", "support"], ["all allies"], [["all attack", "all defense"]], ["mutant"], [["debuff cleanse"]])
Blade = Characters("Blade", "combat", "male", "human", "hero", "physical", "none", ["healing", "weapons master"], ["leader"], ["weapons master"], [["all attack"]])
BetaRayBill = Characters("Beta Ray Bill", "universal", "male", "alien", "hero", "energy", "fire", ["flame", "leadership", "annihilator"], ["leader", "support"], ["all allies"], [["fire"]], ["alien"], [["villain"]])
Cyclops = Characters("Cyclops", "blast", "male", "mutant", "hero", "energy", "none", ["energy projection", "command"], ["leader", "support"], ["all allies"], [["all attack", "all defense"]], ["all allies"], [["energy"]])
Gladiator = Characters("Gladiator", "combat", "male", "alien", "hero", "physical", "none", ["annihilators", "strong", "leadership"], ["leader"], ["all allies"], [["all attack"]])
Hela = Characters("Hela", "universal", "female", "alien", "villain", "energy", "none", ["command", "pure evil"], ["leader", "support"], ["all allies"], [["energy"]], ["all allies"], [["ignore dodge", "hero", "dr hero"]])
MadelynePryor = Characters("Madelyne Pryor", "blast", "female", "mutant", "villain", "energy", "mind", ["mind", "mind resist"], ["leader"], ["all allies"], [["debuff cleanse"]])
Mystique = Characters("Mystique", "speed", "female", "mutant", "villain", "physical", "none", ["agility", "weapons master"], ["support"], [], [[]], ["all allies"], [["villain", "hero"]])
Rogue = Characters("Rogue", "speed", "female", "mutant", "hero", "physical", ["mind", "cold", "lightning"], ["healing", "fast movement"])
SilverSurfer = Characters("Silver Surfer", "universal", "male", "alien", "villain", "energy", "none", ["power cosmic", "symbiote", "annihilators"], ["leader"], ["all allies"], ["better debuff cleanse"])
BlackSwan = Characters("Black Swan", "speed", "female", "alien", "villain", "energy", "none", ["pure evil", "black order"], ["leader"], ["all allies"], [["debuff cleanse"]])
Hellstorm = Characters("Hellstorm", "universal", "male", "human", "hero", "energy", "fire", ["magic", "flame"])
Satana = Characters("Satana", "universal", "female", "human", "hero", "energy", "fire", ["magic", "flame"], ["leader", "support"], ["all allies"], [["fire"]], ["all allies"], [["all elem"]])
BlueMarvel = Characters("Blue Marvel", "universal", "male", "human", "hero", "energy", "none", ["leadership", "energy projection"], ["support"], [], [[]], ["all allies"], [["all resist"]])
Crescent = Characters("Crescent", "combat", "female", "human", "hero", "physical", "none", ["leadership", "durability", "strong"], ["leader"], ["all allies"], ["physical"])
Daredevil = Characters("Daredevil", "speed", "male", "human", "hero", "physical", "none", ["heightened senses", "defenders", "leadership"])
DoctorDoom = Characters("Doctor Doom", "universal", "male", "human", "villain", "energy", "none", ["pure evil", "magic"], ["leader"], ["all allies"], [["debuff cleanse"]])
Dormammu = Characters("Dormammu", "universal", "male", "other", "villain", "energy", "fire", ["magic", "pure evil"], ["leader"], ["villain"], [["hero"]])
EbonyMaw = Characters("Ebony Maw", "blast", "male", "alien", "villain", "energy", "mind", ["pure evil", "mind resist", "black order"], ["leader", "support"], ["all allies"], [["energy"]], ["all allies"], [["damage to universal", "dr universal"]])
Elektra = Characters("Elektra", "speed", "female", "human", "hero", "physical", "none", ["weapons master"])
EmmaFrost = Characters("Emma Frost", "blast", "female", "mutant", "hero", "energy", "mind", ["mind resist", "durability"])
Falcon = Characters("Falcon", "speed", "male", "human", "villain", "physical", "none", ["fast movement", "leadership", "zombie"], ["support"], [], [[]], ["zombie"], [["hero", "villain"]])
Gorr = Characters("Gorr", "universal", "male", "alien", "villain", "physical", "none", ["healing", "pure evil", "fast movement"], ["leader"], ["villain"], [["hp", "debuff cleanse"]])
GreenGoblin = Characters("Green Goblin", "speed", "male", "human", "villain", "energy", "fire", ["flame", "fast movement", "sinister six"], ["leader", "support"], ["all allies"], [["all attack", "ignore dodge"]], ["villain"], [["villain", "hero"]])
Groot = Characters("Groot", "combat", "male", "alien", "hero", "physical", "none", ["healing", "guardians of the galaxy"], ["support"], [], [[]], ["guardians of the galaxy"], [["damage to boss", "heal when hit"]])
Gwenpool = Characters("Gwenpool", "speed", "female", "human", "villain", "physical", "none", ["agility"])
Nicepool = Characters("Nicepool", "speed", "male", "mutant", "hero", "physical", "none", ["healing", "weapons master"], ["leader"], ["all allies", "Handsomepool"], [["all attack", "all defense"], ["damage to boss"]])
Deadpool = Characters("Deadpool", "speed", "male", "mutant", "hero", "physical", "none", ["healing", "weapons master"], ["leader"], ["all allies", "Deadpool"], [["all attack", "all defense"], ["debuff cleanse"]])
Echo = Characters("Maya Lopez (Echo)", "speed", "female", "human", "hero", "physical", "none", ["agility"], ["leader", "support"], ["speed"], [["all attack", "all defense", "debuff cleanse"]], ["speed"], [["ignore dodge", "chain hit"]])
Angel = Characters("Angel", "speed", "male", "mutant", "hero", "physical", "none", ["leadership", "fast movement"], ["leader", "support"], ["all allies"], [["dodge", "recovery rate"]], ["all allies"], [["debuff cleanse"]])
Havok = Characters("Havok", "blast", "male", "mutant", "hero", "energy", "none", "energy projection", ["leader"], ["all allies"], [["energy"]])
Hawkeye = Characters("Hawkeye", "speed", "male", "human", "hero", "physical", "none", ["weapons master", "agent"])
Hyperion = Characters("Hyperion", "universal", "male", "alien", "hero", "energy", "fire", ["leadership", "eternals", "phoenix force"], ["leader"], ["all allies"], [["all attack"]])
Iceman = Characters("Iceman", "blast", "male", "mutant", "hero", "energy", "cold", ["chill", "cold blooded"])
Ikaris = Characters("Ikaris", "universal", "male", "alien", "hero", "energy", "none", ["energy projection", "leadership", "eternals"], ["leader"], ["eternals"], [["all attack"]])
Kingpin = Characters("Kingpin", "combat", "male", "human", "villain", "physical", "none", ["strong", "command"], ["leader"], ["villain"], [["physical", "hp"]])
KittyPryde = Characters("Kitty Pryde", "speed", "female", "mutant", "hero", "physical", "none", ["command", "weapons master"], ["leader"], ["mutant"], [["all attack"]])
Knull = Characters("Knull", "universal", "male", "alien", "villain", "physical", "none", ["symbiote", "strong", "pure evil"], ["leader"], ["symbiote"], [["all attack"]])
Modok = Characters("M.O.D.O.K.", "blast", "male", "human", "villain", "energy", "mind", ["mind", "machine", "pure evil"], ["leader"], ["all allies"], [["energy"]])
Magik = Characters("Magik", "blast", "female", "mutant", "hero", "energy", "none", ["magic", "mind resist"], ["leader"], ["mutant"], [["all attack"]])
Mephisto = Characters("Mephisto", "blast", "male", "other", "villain", "energy", "fire", ["hellfire", "magic", "pure evil"], ["leader"], ["villain"], [["debuff cleanse"]])
MrFantastic = Characters("Mr. Fantastic", "combat", "male", "human", "hero", "physical", "none", ["durability", "leadership", "fantastic four"], ["leader"], ["fantastic four"], [["all attack"]])
MoleculeMan = Characters("Molecule Man", "universal", "male", "human", "villain", "energy", "none", ["fast movement", "energy projection"], ["leader", "support"], ["all allies"], [["ignore damage inc/dec effect", "decrease chain hit", "debuff cleanse"]], ["all allies"], [["reflect all"]])
MorganLeFay = Characters("Morgan Le Fay", "universal", "female", "human", "villain", "energy", "none", ["magic", "pure evil"], ["support"], [], [[]], ["universal"], [["all attack", "damage to boss", "debuff cleanse"]])
OmegaRed = Characters("Omega Red", "combat", "male", "mutant", "villain", "physical", "none", ["healing", "pure evil", "strong"], ["leader"], ["Omega Red"], [["physical"]])
PhilCoulson = Characters("Phil Coulson", "blast", "male", "human", "hero", "energy", "none", ["command", "agent"], ["support"], [], [[]], ["all allies", "hero"], [["guaranteed crit rate", "villain", "dr villain"], ["hp", "dr"]])
Polaris = Characters("Polaris", "blast", "female", "mutant", "hero", "energy", "none", ["energy projection", "fast movement"], ["leader", "support"], ["mutant"], [["all attack"]], ["mutant"], [["villain", "dr villain"]])
ProximaMidnight = Characters("Proxima Midnight", "universal", "female", "alien", "villain", "energy", "none", ["agility", "fast movement", "black order"], ["leader", "support"], ["all allies"], [["ignore dodge", "crit damage"]], ["villain"], [["villain", "hero"]])
Punisher = Characters("Punisher", "combat", "male", "human", "hero", "physical", "none", ["leadership", "weapons master"], ["leader"], ["all allies"], [["all attack"]])
Quicksilver = Characters("Quicksilver", "speed", "male", "other", "hero", "physical", "none", ["fast movement", "agility"])
RocketRaccoon = Characters("Rocket Raccoon", "blast", "male", "alien", "hero", "energy", "none", ["weapons master", "guardians of the galaxy"], ["support"], [], [[]], ["guardians of the galaxy"], [["energy"]])
Ronan = Characters("Ronan", "universal", "male", "alien", "hero", "energy", "none", ["mind resist", "command", "annihilators"], ["leader", "support"], ["universal"], [["all attack", "all defense"]], ["universal"], [["ignore dodge", "villain", "hero"]])
Sabretooth = Characters("Sabretooth", "combat", "male", "mutant", "villain", "physical", "none", ["pure evil", "agility"])
ScarletSpider = Characters("Chasm", "speed", "male", "human", "villain", "physical", "none", ["spider-sense", "leadership", "agility"], ["support"], [], [[]], ["spider-sense"], [["villain", "hero", "skill damage bonus damage"]])
ScarletWitch = Characters("Scarlet Witch", "universal", "female", "other", "hero", "energy", "mind", ["chaos magic", "fast movement"], ["leader"], ["all allies"], [["energy"]])
Sentry = Characters("Sentry", "universal", "male", "human", "hero", "energy", "none", ["dark avengers", "leadership", "energy projection"], ["leader"], ["all allies"], [["all attack", "debuff cleanse"]])
ShangChi = Characters("Shang-Chi", "combat", "male", "human", "hero", "physical", "none", ["agility", "leadership"], ["leader"], ["all allies"], [["all attack"]])
SheHulk = Characters("She-Hulk", "combat", "female", "human", "hero", "physical", "none", ["gamma radiation", "durability"], ["leader"], ["all allies"], [["male"]])
Shuri = Characters("Shuri", "speed", "female", "human", "hero", "physical", "none", ["heightened senses", "leadership"], ["leader", "support"], ["speed"], [["all attack"]], ["all allies"], [["villain", "dr villain"]])
Sin = Characters("Sin", "speed", "female", "human", "villain", "physical", "none", ["weapons master", "pure evil"], ["leader", "support"], ["all allies"], [["all attack"]], ["villain"], [["damage to boss"]])
SisterGrimm = Characters("Sister Grimm", "blast", "female", "human", "hero", "energy", "fire", ["magic"], ["support"], [], [[]], ["magic"], [["debuff cleanse", "heal when debuffed"]])
SpiderMan2099 = Characters("Spider-Man 2099", "speed", "male", "human", "hero", "physical", "none", ["spider-sense", "leadership", "agility"], ["leader"], ["all allies"], [["ignore dodge"]])
SquirrelGirl = Characters("Squirrel Girl", "speed", "female", "human", "villain", "physical", "none", ["agility", "pure evil", "power cosmic"], ["support"], [], [[]], ["Thanos"], [["damage to boss"]])
Stryfe = Characters("Stryfe", "blast", "male", "mutant", "villain", "energy", "none", ["pure evil", "energy projection"], ["leader", "support"], [], [[]], ["all allies"], [["debuff cleanse"]])
Taskmaster = Characters("Taskmaster", "combat", "male", "human", "villain", "physical", "none", ["weapons master", "pure evil"], ["leader", "support"], ["Taskmaster"], [["all attack", "all defense"]], ["weapons master", "all allies"], [["guaranteed crit rate", "ignore dodge", "skill damage bonus damage"], ["villain", "hero"]])
Thena = Characters("Thena", "universal", "female", "alien", "hero", "physical", "none", ["leadership", "eternals"], ["leader"], ["all allies"], [["all attack", "all defense"]])
JaneFoster = Characters("Thor (Jane Foster)", "universal", "female", "human", "hero", "energy", "lightning", ["shock", "fast movement"], ["leader", "support"], ["all allies"], [["lightning resist"]], ["shock"], [["ignore dodge", "lightning"]])
Ultron = Characters("Infinity Ultron", "universal", "male", "other", "villain", "energy", "none", ["machine", "pure evil"], ["leader"], ["machine"], [["all attack"]])
Vision =  Characters("Vision", "universal", "male", "creature", "hero", "physical", "none", ["fast movement", "machine", "durability"], ["leader"], ["all allies", "Scarlet Witch"], [["all attack"], ["all attack"]])
WarMachine = Characters("War Machine", "blast", "male", "human", "hero", "physical", "none", ["machine", "leadership"], ["leader", "support"], ["blast"], [["all attack"]], ["machine"], [["villain", "dr villain", "hp"]])
Wenwu = Characters("Wenwu", "blast", "male", "human", "villain", "energy", "none", ["agility", "pure evil"], ["leader", "support"], ["villain"], [["debuff cleanse", "heal when debuffed"]], ["villain"], [["hp"]])
WhiteFox = Characters("White Fox", "speed", "female", "human", "hero", "physical", "cold", ["agility", "agent", "leadership"], ["leader", "support"], ["all allies"], [["debuff effect increase"]], ["leadership", "hero"], [["villain", "dr villain"], ["all attack", "chain hit", "ignore dodge"]])
WinterSoldier = Characters("Winter Soldier", "speed", "male", "human", "hero", "physical", "none", ["weapons master", "leadership"], ["leader"], ["all allies"], [["physical"]])
Wong = Characters("Wong", "speed", "male", "human", "villain", "physical", "none", ["magic", "weapons master", "zombie"], ["support"], [], [[]], ["magic"], [["hero", "villain"]])
AbsorbingMan = Characters("Absorbing Man", "combat", "male", "human", "villain", "physical", "none", ["strong"])
Aero = Characters("Aero", "speed", "female", "human", "hero", "energy", "none", ["leadership", "fast movement"])
AgentVenom = Characters("Agent Venom", "combat", "male", "human", "hero", "physical", "none", ["symbiote", "leadership", "agent"], ["leader", "support"], ["all allies"], [["physical"]], ["symbiote"], [["decrease chain hit", "chain hit"]])
AmericaChavez = Characters("America Chavez", "combat", "female", "human", "hero", "physical", "none", ["strong", "fast movement"], ["leader", "support"], ["all allies"], [["all attack"]], ["all allies"], [["hp", "reflect all"]])
Arachknight = Characters("Arachknight", "speed", "male", "human", "hero", "physical", "none", ["spider-sense", "leadership", "infinity warps"], ["leader"], ["infinity warps"], [["all attack"]])
Ares = Characters("Ares", "combat", "male", "alien", "hero", "physical", "none", ["dark avengers", "weapons master", "strong"], ["leader"], ["all allies"], [["physical"]])
BaronMordo = Characters("Mordo", "speed", "male", "human", "hero", "energy", "none", ["agility", "heightened senses", "magic"])
Beast = Characters("Beast", "combat", "male", "mutant", "hero", "physical", "none", ["strong", "agility"], ["leader", "support"], ["all allies"], [["physical", "crit damage"]], ["all allies"], [["hp", "ignore dodge"]])
Bishop = Characters("Bishop", "blast", "male", "mutant", "hero", "energy", "none", ["energy projection"], ["leader"], ["all allies"], [["energy"]])
BlackDwarf = Characters("Black Dwarf", "combat", "male", "alien", "villain", "physical", "none", ["black order", "durability", "strong"], ["support"], [], [[]], ["black order"], [["reflect physical", "guard break immunity"]])
AntiMan = Characters("Anti-Man", "universal", "male", "human", "villain", "energy", "none", ["fast movement", "energy projection"], ["leader"], ["all allies"], [["all attack", "hp"]])
Bullseye = Characters("Bullseye", "speed", "male", "human", "villain", "physical", "none", ["dark avengers", "weapons master"], ["leader"], ["all allies"], [["ignore dodge"]])
Clea = Characters("Clea", "universal", "female", "alien", "hero", "energy", "none", ["magic", "fast movement"])
Colossus = Characters("Colossus", "combat", "male", "mutant", "hero", "physical", "none", ["strong", "leadership"], ["support"], [], [[]], ["all allies"], [["decrease phys reflect", "dr villain", "dr hero"]])
CorvusGlaive = Characters("Corvus Glaive", "speed", "male", "alien", "villain", "physical", "none", ["agility", "fast movement", "black order"])
Destroyer = Characters("Destroyer", "universal", "no gender", "creature", "neutral", "energy", "none", ["energy projection", "machine"])
DoctorVoodoo = Characters("Doctor Voodoo", "universal", "male", "human", "hero", "energy", "none", ["magic", "command"], ["leader", "support"], ["all allies"], [["debuff effect increase", "all attack"]], ["all allies"], [["dodge"]])
Domino = Characters("Domino", "speed", "female", "mutant", "hero", "physical", "none", ["agility", "weapons master"], ["leader"], ["all allies"], [["ignore dodge"]])
Drax = Characters("Drax", "combat", "male", "alien", "hero", "physical", "none", ["healing"], ["leader"], ["all allies"], [["hp"]])
Electro = Characters("Electro", "speed", "male", "human", "villain", "energy", "lightning", ["pure evil", "shock", "sinister six"], ["leader", "support"], ["sinister six"], [["all attack", "all defense"]], ["all allies"], [["lightning"]])
HumanTorch = Characters("Human Torch", "blast", "male", "human", "hero", "energy", "fire", ["flame", "fast movement", "fantastic four"], ["leader"], ["all allies"], [["fire resist"]])
InvisibleWoman = Characters("Invisible Woman", "blast", "female", "human", "hero", "energy", "none", ["energy projection", "fantastic four"], ["leader", "support"], ["all allies"], [["energy"]], ["all allies"], [["debuff cleanse"]])
ElsaBloodstone = Characters("Elsa Bloodstone", "speed", "female", "human", "hero", "physical", "none", ["weapons master"], ["leader"], ["all allies"], [["physical"]])
Gambit = Characters("Gambit", "blast", "male", "mutant", "hero", "energy", "none", ["agility", "mind"], ["leader"], ["all allies"], [["ignore dodge"]])
GhostPanther = Characters("Ghost Panther", "universal", "male", "human", "hero", "physical", "fire", ["agility", "flame", "infinity warps"], ["leader", "support"], ["all allies"], [["crit rate", "fire"]], ["all allies"], [["fire", "villain", "dr villain"]])
RobbieReyes = Characters("Ghost Rider (Robbie Reyes)", "universal", "male", "human", "hero", "energy", "fire", ["fast movement", "flame"], ["leader", "support"], ["all allies"], [["ignore dodge"]], ["flame"], [["fire resist", "fire"]])
GiantMan = Characters("Giant-Man", "universal", "male", "human", "villain", "physical", "none", ["strong"], ["leader"], ["all allies"], [["hp"]])
Gilgamesh = Characters("Gilgamesh", "combat", "male", "alien", "hero", "physical", "none", ["strong", "eternals"], ["support"], [], [[]], ["eternals"], [["all defense", "decrease chain hit", "decrease phys reflect"]])
KateBishop = Characters("Hawkeye (Kate Bishop)", "speed", "female", "human", "hero", "physical", "none", ["agility", "agent"])
Heimdall = Characters("Heimdall", "universal", "male", "alien", "hero", "physical", "none", ["strong", "leadership"], ["leader"], ["all allies"], [["all defense", "ignore dodge"]])
HopeSummers = Characters("Hope Summers", "combat", "female", "mutant", "hero", "physical", "none", ["phoenix force", "strong"], ["leader"], ["mutant", "Cable"], [["all attack"], ["all attack"]])
AmadeusCho = Characters("Hulk (Amadeus Cho)", "combat", "male", "human", "hero", "physical", "none", ["gamma radiation", "durability"])
Hulkbuster = Characters("Hulkbuster (Iron Man Mark 44)", "combat", "male", "creature", "hero", "physical", "none", ["strong", "machine"], ["leader", "support"], ["all allies", "Iron Man"], [["all attack"], ["all attack"]], ["machine"], [["hp"]])
Ikon = Characters("Ikon", "speed", "female", "alien", "hero", "energy", "none", ["agility", "energy projection", "annihilators"])
IronFist = Characters("Iron Fist", "combat", "male", "human", "hero", "energy", "none", ["agility", "healing", "defenders"], ["leader"], ["defenders"], [["all attacks"]])
IronHammer = Characters("Iron Hammer", "universa", "male", "alien", "hero", "energy", "lightning", ["machine", "shock", "infinity warps"], ["leader"], ["all allies"], [["energy", "lightning"]])
Ironheart = Characters("Ironheart", "blast", "female", "human", "hero", "energy", "none", ["machine", "leadership"], ["leader", "support"], ["blast"], [["energy"]], ["all allies"], [["ignore dodge", "damage to boss"]])
JessicaJones = Characters("Jessica Jones", "combat", "female", "human", "hero", "physical", "none", ["strong", "durability", "defenders"], ["support"], [], [[]], ["defenders"], [["emergency heal", "all attack", "mind immunity"]])
Juggernaut = Characters("Juggernaut", "combat", "male", "mutant", "villain", "physical", "none", ["strong", "durability", "pure evil"])
Kaecilius = Characters("Kaecilius", "blast", "male", "human", "villain", "energy", "none", ["magic", "agility"])
Psylocke = Characters("Psylocke", "blast", "female", "mutant", "hero", "energy", "mind", ["agility", "mind"])
CassandraNova = Characters("Cassandra Nova", "blast", "female", "mutant", "villain", "energy", "mind", ["mind", "mind resist", "pure evil"], ["leader"], ["mutant"], [["debuff cleanse"]])
Yondu = Characters("Yondu", "speed", "male", "alien", "hero", "physical", "none", ["command", "weapons master"], ["support"], [], [[]], ["alien"], [["villain", "all attack", "damage to boss"]])
x23 = Characters("X-23", "speed", "female", "mutant", "hero", "physical", "none", ["agility", "healing"])
Kahhori = Characters("Kahhori", "blast", "female", "human", "hero", "energy", "none", ["energy projection", "fast movement", "cosmic cube"], ["support"], [], [[]], ["hero"], [["damage to cleansed"]])
Katy = Characters("Katy", "speed", "female", "human", "hero", "physical", "none", ["weapons master", "agility"], ["leader", "support"], ["all allies", "Shang-Chi"])
KidOmega = Characters("Kid Omega", "blast", "male", "mutant", "hero", "energy", "mind", ["phoenix force", "energy projection"], ["leader"], ["all allies"], [["mind"]])
Kingo = Characters("Kingo", "blast", "male", "alien", "hero", "energy", "none", ["eternals", "leadership", "energy projection"])
Kraven = Characters("Kraven The Hunter", "speed", "male", "human", "villain", "physical", "none", ["weapons master", "agility", "sinister six"], ["support"], [], [[]], ["sinister six"], [["villain", "hero", "skill damage bonus damage"]])
LincolnCampbell = Characters("Lincoln Campbell", "blast", "male", "inhuman", "hero", "energy", "lightning", ["shock"], ["leader"], ["all allies"], [["lightning"]])
Lizard = Characters("Lizard", "combat", "male", "human", "villain", "physical", "none", ["healing", "sinister six"], ["leader"], ["all allies"], [["physical"]])
LukeCage = Characters("Luke Cage", "combat", "male", "human", "hero", "physical", "none", ["strong", "durability", "defenders"], ["leader", "support"], ["defenders"], [["better debuff cleanse"]], ["defenders"], [["ignore dodge"]])
Makkari = Characters("Makkari", "speed", "female", "alien", "hero", "physical", "none", ["eternals", "leadership", "fast movement"])
ManThing = Characters("Man-Thing", "combat", "male", "human", "hero", "physical", "none", ["strong", "healing", "magic"], ["leader"], ["all allies"], [["hp"]])
Mantis = Characters("Mantis", "blast", "female", "alien", "hero", "energy", "mind", ["mind", "healing", "guardians of the galaxy"], ["support"], [], [[]], ["dr villain", "dr hero"])
Medusa = Characters("Medusa", "universal", "female", "inhuman", "hero", "physical", "none", ["command"], ["leader", "support"], ["universal"], [["all attack"]], ["inhuman"], [["villain"]])
MisterSinister = Characters("Mister Sinister", "blast", "male", "mutant", "villain", "energy", "mind", ["pure evil", "energy projection", "healing"], ["leader"], ["all allies"], [["mind resist"]])
MoonGirl = Characters("Moon Girl", "blast", "female", "inhuman", "hero", "physical", "lightning", ["weapons master", "leadership"], ["leader"], ["all allies"], [["all attack"]])
Moonstone = Characters("Moonstone", "blast", "female", "human", "villain", "energy", "none", ["dark avengers", "energy projection"])
Morbius = Characters("Morbius", "combat", "male", "human", "villain", "physical", "none", ["strong", "agility"], ["leader"], ["all allies"], [["hp"]])
Nebula = Characters("Nebula", "combat", "female", "alien", "hero", "physical", ["fire", "lightning"], ["weapons master", "machine"])
Nightcrawler = Characters("Nightcrawler", "speed", "male", "mutant", "hero", "physical", "none", ["agility", "leadership"])
SamAlexander = Characters("Nova (Sam Alexander)", "universal", "male", "human", "hero", "energy", "none", ["fast movement", "energy projection"])
AvrilKincaid = Characters("Quasar (Avril Kincaid)", "universal", "female", "human", "hero", "energy", "none", ["heightened senses", "energy projection"])
WendellVaughn = Characters("Quasar (Wendell Vaughn)", "universal", "male", "human", "hero", "energy", "none", ["energy projection", "fast movement", "annihilators"], ["leader"], ["annihilators"], [["hp", "debuff cleanse"]])
RachelSummers = Characters("Rachel Summers", "universal", "female", "mutant", "hero", "energy", "fire", ["phoenix force", "fast movement"], ["leader"], ["phoenix force"], [["mind resist", "debuff cleanse"]])
RedGuardian = Characters("Red Guardian", "combat", "male", "human", "hero", "physical", "none", ["strong", "agility"], ["leader"], ["hero"], [["hp"]])
RedSkull = Characters("Red Skull", "blast", "male", "human", "villain", "physical", "none", ["pure evil", "command", "cosmic cube"])
Rescue = Characters("Rescue", "blast", "female", "human", "hero", "energy", "none", ["machine", "leadership"], ["support"], [], [[]], ["all allies"], [["hp", "recovery rate"]])
Rhino = Characters("Rhino", "combat", "male", "human", "villain", "physical", "none", ["strong", "durability", "sinister six"])
Sandman = Characters("Sandman", "combat", "male", "human", "villain", "physical", "none", ["durability", "sinister six"])
Scorpion = Characters("Scorpion", "speed", "male", "human", "villain", "physical", "poison", ["pure evil", "durability", "poison"])
Scream = Characters("Scream", "combat", "female", "human", "hero", "physical", "none", ["strong", "leadership", "symbiote"])
Sersi = Characters("Sersi", "blast", "female", "alien", "hero", "energy", "none", ["eternals", "leadership", "magic"], ["support"], [], [[]], ["eternals"], [["all attack", "villain", "dr villain", "debuff cleanse"]])
Sif = Characters("Sif", "combat", "female", "alien", "hero", "physical", "none", ["agility"], ["leader", "support"], ["combat"], [["hp", "physical"]], ["all allies"], [["damage to boss"]])
Silk = Characters("Silk", "speed", "female", "human", "hero", "physical", "none", ["spider-sense", "agility"])
Skurge = Characters("Skurge", "combat", "male", "alien", "villain", "physical", "none", ["strong", "durability"])
SpiderWoman = Characters("Spider-Woman", "blast", "female", "human", "hero", "energy", "lightning", ["spider-sense", "leadership", "agility"], ["leader", "support"], ["spider-sense"], [["all attack", "debuff cleanse"]], ["spider-sense"], [["decrease chain hit", "ignore dodge", "damage to boss"]])
Spot = Characters("Spot", "speed", "male", "human", "villain", "physical", "none", ["fast movement", "pure evil"])
SunBird = Characters("Sun Bird", "speed", "male", "human", "hero", "physical", "fire", ["warriors of the sky", "agility", "flame"], ["support"], [], [[]], ["warriors of the sky"], [["revive"]])
Supergiant = Characters("Supergiant", "universal", "female", "alien", "villain", "energy", "mind", ["mind", "mind resist", "black order"], ["leader"], ["all allies"], [["debuff cleanse"]])
SwordMaster = Characters("Sword Master", "combat", "male", "human", "hero", "physical", "none", ["leadership", "weapons master"], ["leader"], ["hero"], [["all defense", "hp"]])
Thing = Characters("The Thing", "combat", "male", "human", "hero", "physical", "none", ["strong", "durability", "fantastic four"], ["support"], [], [[]], ["fantastic four"], [["all attack", "reflect all", "damage to boss", "all defense", "hp"]])
Titania = Characters("Titania", "combat", "female", "human", "villain", "physical", "none", ["strong"], ["leader", "support"], ["combat"], [["physical"]], ["strong"], [["all attack"]])
Toxin = Characters("Toxin", "combat", "male", "human", "hero", "physical", "none", ["agility", "symbiote", "strong"], ["leader"], ["all allies"], [["physical"]])
Valkyrie = Characters("Valkyrie", "combat", "female", "alien", "hero", "physical", "none", ["strong"], ["support"], [], [[]], ["all allies"], [["ignore dodge", "villain", "dr villain"]])
Vulture = Characters("Vulture", "speed", "male", "human", "hero", "physical", "none", ["fast movement", "agility", "sinister six"])
WarTiger = Characters("War Tiger", "combat", "male", "human", "hero", "physical", "none", ["warriors of the sky", "strong", "durability"])
Warpath = Characters("Warpath", "combat", "male", "mutant", "hero", "physical", "none", ["strong", "leadership"])
Wasp = Characters("Wasp", "blast", "female", "human", "hero", "energy", "none", ["fast movement"], ["leader", "support"], ["all allies"], [["all attack", "all defense"]], ["all allies"], [["hp", "debuff cleanse"]])
NadiaVanDyne = Characters("Wasp (Nadia Van Dyne)", "blast", "female", "human", "hero", "energy", "none", ["agent", "fast movement"])
Wave = Characters("Wave", "speed", "female", "human", "hero", "energy", "none", ["heightened senses", "agility"], ["leader", "support"], ["all allies", "Namor"], [["all attack"], ["all attack"]], ["hero"], [["villain", "dr villain"]])
WeaponHex = Characters("Weapon Hex", "blast", "female", "mutant", "villain", "energy", "none", ["zombie", "healing", "chaos magic"], ["support"], [], [[]], ["zombie"], [["TIFBD", "hero", "villain", "debuff cleanse"]]) #TIFBD = Temporary Immunity Followed By Death
YelenaBelova = Characters("Yelena Belova", "speed", "female", "human", "hero", "physical", "none", ["agility", "agent"])
Thane = Characters("Thane", "universal", "male", "inhuman", "villain", "physical", "fire", ["phoenix force", "durability", "pure evil"], ["leader"], ["all allies"], [["better debuff cleanse"]])
Fandral = Characters("Fandral", "speed", "male", "alien", "hero", "physical", "none", ["agility"])
Volstagg = Characters("Volstagg", "combat", "male", "alien", "hero", "physical", "none", ["durability"], ["support"], [], [[]], ["hero"], [["dr"]])
Hogun = Characters("Hogun", "combat", "male", "alien", "hero", "physical", "none", ["strong"], ["leader"], ["all allies"], [["all attack"]])
FranklinRichards = Characters("Franklin Richards", "universal", "male", "human", "hero", "energy", "none", ["energy projection", "mind", "fantastic four"], ["support"], [], [[]], ["fantastic four"], [["emergency heal"]])
ValeriaRichards = Characters("Valeria Richards", "blast", "female", "human", "hero", "energy", "none", ["leadership", "fantastic four"], ["leader"], ["fantastic four"], [["hp", "all attack"]])
Victorius = Characters("Victorius", "universal", "female", "human", "villain", "hp", "none", ["fast movement", "energy projection"], ["leader", "support"], ["all allies", "Doctor Doom"], [["all attack"], ["energy attack"]], ["all allies"], [["hp"]])
Dazzler = Characters("Dazzler", "blast", "female", "mutant", "hero", "energy", "none", ["energy projection"], ["support"], [], [[]], ["mutant"], [["ignore dodge", "damage to boss"]])
Jubilee = Characters("Jubilee", "blast", "female", "mutant", "hero", "energy", "none", ["energy projection"])
Negasonic = Characters("Negasonic Teenage Warhead", "blast", "female", "mutant", "hero", "energy", "none", ["agility", "fast movement", "energy projection"])
Daken = Characters("Daken", "combat", "male", "mutant", "villain", "physical", "none", ["weapons master", "healing"])
Hulkling = Characters("Hulkling", "combat", "male", "alien", "hero", "physical", "none", ["strong", "durability"])
Wiccan = Characters("Wiccan", "blast", "male", "human", "hero", "energy", "none", ["fast movement", "energy projection"], ["leader", "support"], ["all allies"], [["all attack"]], ["all allies"], [["ignore dodge"]])
Abomination = Characters("Abomination", "combat", "male", "human", "villain", "physical", "none", ["gamma radiation", "durability", "zombie"], ["leader", "support"], ["zombie"], [["all attack"]], ["gamma radiation"], [["ignore dodge", "villain", "hero"]])
Agent13 = Characters("Agent 13", "speed", "female", "human", "hero", "physical", "none", ["agent"])
Zemo = Characters("Baron Zemo", "speed", "male", "human", "villain", "physical", "none", ["agility", "pure evil"], ["leader"], ["villain"], [["all attack", "ignore dodge"]])
BlackCat = Characters("Black Cat", "speed", "female", "human", "villain", "physical", "none", ["agility"], ["leader", "support"], ["villain"], [["all attack", "ignore dodge"]], ["all allies"], [["debuff effect increase"]])
CassieLang = Characters("Cassie Lang", "blast", "female", "human", "hero", "energy", "none", ["fast movement", "agility"], ["support"], [], [[]], ["speed"], [["ignore dodge", "hero", "villain"]])
Crossbones = Characters("Crossbones", "combat", "male", "human", "villain", "physical", "none", ["weapons master"], ["leader"], ["all allies"], [["physical"]])
Crystal = Characters("Crystal", "blast", "female", "inhuman", "hero", ["energy"], ["fire", "cold"], ["command", "energy projection", "fantastic four"], ["leader"], ["all allies"], [["energy"]])
Quake = Characters("Daisy Johnson", "blast", "female", "inhuman", "hero", "energy", "none", ["mind resist", "agent"])
Darkhawk = Characters("Darkhawk", "speed", "male", "human", "hero", "energy", "none", ["leadership", "fast movement"])
Deathlok = Characters("Deathlok", "blast", "male", "human", "hero", "physical", "none", ["machine", "agent"], ["leader"], ["all allies"], [["physical"]])
Exodus = Characters("Exodus", "universal", "male", "mutant", "hero", "energy", "none", ["energy projection", "command"], ["support"], [], [[]], ["mutant"], [["debuff cleanse"]])
Fantomex = Characters("Fantomex", "speed", "male", "mutant", "hero", "physical", "none", ["agility", "weapons master"])
Ghost = Characters("Ghost", "speed", "female", "human", "villain", "energy", "none", ["weapons master", "machine"], ["leader", "support"], ["machine"], [["all attack"]], ["all allies"], [["energy"]])
Goliath = Characters("Goliath", "combat", "male", "human", "hero", "physical", "none", ["strong", "durability"], ["leader"], ["all allies"], [["physical"]])
Gorgon = Characters("Gorgon", "combat", "male", "inhuman", "hero", "physical", "none", ["strong"], ["leader"], ["all allies"], [["physical"]])
GorillaMan = Characters("Gorilla-Man", "combat", "male", "human", "hero", "physical", "none", ["strong", "agility", "weapons master"])
Hellcat = Characters("Hellcat", "speed", "female", "human", "hero", "physical", "none", ["agility"])
HydroMan = Characters("Hydro-Man", "blast", "male", "human", "villain", "physical", "none", ["pure evil"])
Inferno = Characters("Inferno", "blast", "male", "inhuman", "hero", "energy", "fire", ["flame"], ["leader"], ["all allies"], [["fire resist"]])
Karnak = Characters("Karnak", "speed", "male", "inhuman", "hero", "physical", "none", ["heightened senses"])
KidKaiju = Characters("Kid Kaiju", "speed", "male", "inhuman", "hero", "physical", "fire", ["command"], ["leader"], ["all allies"], [["all attack", "all defense"]])
Killmonger = Characters("Erik Killmonger (Black Panther)", "combat", "male", "human", "villain", "physical", "none", ["strong", "command"])
MBaku = Characters("M'Baku", "combat", "male", "human", "hero", "physical", "none", ["leaderhsip", "strong"], ["leader", "support"], ["all allies"], [["physical"]], ["all allies"], [["villain", "dr villain"]])
Lash = Characters("Lash", "blast", "male", "inhuman", "villain", "energy", "none", ["energy projection"], ["leader"], ["all allies"], [["energy"]])
Maximus = Characters("Maximus", "blast", "male", "inhuman", "villain", "energy", "lightning", ["mind resist", "pure evil"])
MistyKnight = Characters("Misty Knight", "speed", "female", "human", "hero", "physical", ["cold", "lightning"], ["agent", "weapons master"], ["leader"], ["all allies"], [["cold"]])
Mockingbird = Characters("Mockingbird", "speed", "female", "human", "hero", "physical", "none", ["agility", "agent"])
MoltenMan = Characters("Molten Man", "combat", "male", "human", "villain", "physical", "fire", ["pure evil", "durability", "flame"], ["leader"], ["all allies"], [["all defense"]])
RichardRider = Characters("Nova (Richard Rider)", "universal", "male", "human", "hero", "energy", "none", ["energy projection", "leadership"], ["leader", "support"], ["hero"], [["energy"]], ["hero"], [["ignore dodge", "villain"]])
PhylaVell = Characters("Phyla-Vell", "universal", "female", "alien", "hero", "energy", "energy", ["energy projection", "leadership"], ["support"], [], [[]], ["universal"], [["all attack", "skill damage bonus damage"]])
RedHulk = Characters("Red Hulk", "combat", "male", "human", "hero", "physical", "fire", ["flame", "gamma radiation", "symbiote"], ["leader"], ["all allies"], [["fire"]])
RedSheHulk = Characters("Red She-Hulk", "combat", "female", "human", "hero", "physical", "fire", ["gamma radiation", "durability", "flame"], ["leader", "support"], ["all allies"], [["fire", "hp"]], ["all allies"], [["hp", "dr"]])
Sentinel = Characters("Sentinel", "universal", "no gender", "other", "villain", "energy", "none", ["machine", "pure evil"], ["leader"], ["all allies"], [["debuff cleanse"]])
Singularity = Characters("Singularity", "universal", "female", "alien", "hero", "energy", "none", ["fast movement", "energy projection"], ["leader"], ["all allies"], [["energy"]])
Slapstick = Characters("Slapstick", "universal", "male", "human", "hero", "physical", "none", ["agility"])
Songbird = Characters("Songbird", "blast", "female", "human", "hero", "energy", "none", ["fast movement", "agent"])
UlyssesKlaue = Characters("Ulysses Klaue", "blast", "male", "human", "villain", "energy", "none", ["weapons master"], ["support"], [], [[]], ["all allies"], [["crit damage"]])
Viper = Characters("Viper", "speed", "female", "human", "villain", "physical", "poison", ["poison", "pure evil"], ["leader"], ["all allies"], [["poison"]])
Warwolf = Characters("Warwolf", "combat", "male", "human", "hero", "physical", "none", ["healing", "agent"], ["support"], [], [[]], ["all allies"], [["crit damage", "guaranteed crit rate"]])
Whiplash = Characters("Whiplash", "blast", "male", "human", "villain", "physical", "lightning", ["shock", "machine"])
WhiteTiger = Characters("White Tiger", "combat", "female", "human", "hero", "physical", "none", ["agility"])
Yellowjacket = Characters("Yellowjacket", "blast", "male", "human", "villain", "energy", "none", ["pure evil", "machine"])
Okoye = Characters("Okoye", "speed", "female", "human", "hero", "physical", "none", ["agility", "weapons master"])

toons = [Odin, Enchantress, Malekith, Ulik, Angela, AdamWarlock, AntMan, BlackBolt, BlackWidow, BlueDragon,
         CaptainAmerica, SharonRogers, Carnage, DoctorOctopus, Gamora, Hulk, Kang, LunaSnow, Mysterio, IronMan,
         JeanGrey, Magneto, MoonKnight, Namor, ProfessorX, ShadowShell, SpiderGwen, SpiderMan, MilesMorales, StarLord,
         Storm, Thanos, Thor, Venom, Wolverine, Sylvie, CaptainMarvel, Loki, NickFury, Korath,
         MinnErva, MsMarvel, Spectrum, BlackPanther, Cable, DoctorStrange, GhostRider, AncientOne, Apocalypse, Blade,
         BetaRayBill, Cyclops, Gladiator, Hela, MadelynePryor, Mystique, Rogue, SilverSurfer, BlackSwan, Hellstorm,
         Satana, BlueMarvel, Crescent, Daredevil, Deadpool, Nicepool, DoctorDoom, Dormammu, EbonyMaw, Elektra, EmmaFrost,
         Falcon, Gorr, GreenGoblin, Groot, Gwenpool, Echo, Angel, Havok, Hawkeye, Hyperion, Iceman, 
         Ikaris, Kingpin, KittyPryde, Knull, Modok, Magik, Mephisto, MrFantastic, MoleculeMan, MorganLeFay,
         OmegaRed, PhilCoulson, Polaris, ProximaMidnight, Punisher, Quicksilver, RocketRaccoon, Ronan, Sabretooth, ScarletSpider,
         ScarletWitch, Sentry, ShangChi, SheHulk, Shuri, Sin, SisterGrimm, SpiderMan2099, SquirrelGirl, Stryfe,
         Taskmaster, Thena, JaneFoster, Ultron, Vision, WarMachine, Wenwu, WhiteFox, WinterSoldier, Wong,
         AbsorbingMan, Aero, AgentVenom, AmericaChavez, Arachknight, Ares, BaronMordo, Beast, Bishop, BlackDwarf,
         AntiMan, Bullseye, Clea, Colossus, CorvusGlaive, Destroyer, DoctorVoodoo, Domino, Drax, Electro, 
         HumanTorch, InvisibleWoman, ElsaBloodstone, Gambit, GhostPanther, RobbieReyes, GiantMan, Gilgamesh, KateBishop, Heimdall, 
         HopeSummers, AmadeusCho, Hulkbuster, Ikon, IronFist, IronHammer, Ironheart, JessicaJones, Juggernaut, Kaecilius,
         Psylocke, CassandraNova, Yondu, x23, Kahhori, Katy, KidOmega, Kingo, Kraven, LincolnCampbell,
         Lizard, LukeCage, Makkari, ManThing, Mantis, Medusa, MisterSinister, MoonGirl, Moonstone, Morbius,
         Nebula, Nightcrawler, SamAlexander, AvrilKincaid, WendellVaughn, RachelSummers, RedGuardian, RedSkull, Rescue, Rhino,
         Sandman, Scorpion, Scream, Sersi, Sif, Silk, Skurge, SpiderWoman, Spot, SunBird, 
         Supergiant, SwordMaster, Thing, Titania, Toxin, Valkyrie, Vulture, WarTiger, Warpath, Wasp, NadiaVanDyne,
         Wave, WeaponHex, YelenaBelova, Thane, Fandral, Volstagg, Hogun, FranklinRichards, ValeriaRichards, Victorius,
         Dazzler, Jubilee, Negasonic, Daken, Hulkling, Wiccan, Abomination, Agent13, Zemo, BlackCat,
         CassieLang, Crossbones, Crystal, Quake, Darkhawk, Deathlok, Exodus, Fantomex, Ghost, Goliath,
         Gorgon, GorillaMan, Hellcat, HydroMan, Inferno, Karnak, KidKaiju, Killmonger, Lash, Maximus,
         MBaku, MistyKnight, Mockingbird, MoltenMan, RichardRider, PhylaVell, RedHulk, RedSheHulk, Sentinel, Singularity,
         Slapstick, Songbird, UlyssesKlaue, Viper, Warwolf, Whiplash, WhiteTiger, Yellowjacket, Okoye]

namedict = {"Sharon Rogers":SharonRogers, "Kang":Kang, "Spider Gwen":SpiderGwen, "Spider Man":SpiderMan, "Spider Man (Miles Morales)":MilesMorales, "Miles Morales":MilesMorales, "Starlord":StarLord, "Star Lord":StarLord, "Fury":NickFury, "Minn Erva":MinnErva, "Ms. Marvel":MsMarvel, "Kamala Khan":MsMarvel, "Ms Marvel":MsMarvel, "Ms Marvel (Kamala Khan)":MsMarvel, "Captain Monical Rambeau":Spectrum, "Monica Rambeau":Spectrum, "Sam Wilson":Falcon, "Captain America (Sam Wilson)":Falcon, "Captain Falcon":Falcon, "Maya Lopez":Echo,"Echo":Echo, "MODOK":Modok, "Modok":Modok, "Mr Fantastic":MrFantastic, "Rocket":RocketRaccoon, "Scarlet Spider":ScarletSpider, "Shang Chi":ShangChi, "She Hulk":SheHulk, "Black Panther (Shuri)":Shuri, "Spider Man 2099":SpiderMan2099, "Jane Foster":JaneFoster, "Mighty Thor":JaneFoster, "Ultron":Ultron, "Baron Mordo":BaronMordo, "Anti Man":AntiMan, "Robbie Reyes":RobbieReyes, "Giant Man":GiantMan, "Kate Bishop":KateBishop, "Amadeus Cho":AmadeusCho, "Hulkbuster":Hulkbuster, "Riri Williams":Ironheart, "Handsomepool":Nicepool, "X 23":x23, "X23":x23, "Kraven":Kraven, "Man Thing":ManThing, "Mr Sinister":MisterSinister, "Mr. Sinister":MisterSinister, "Sam Alexander":SamAlexander, "Avril Kincaid":AvrilKincaid, "Wendell Vaughn":WendellVaughn, "Spider Woman":SpiderWoman, "Thing":Thing, "Nadia Van Dyne":NadiaVanDyne, "Negasonic":Negasonic, "Zemo":Zemo, "Daisy Johnson":Quake, "Gorilla Man":GorillaMan, "Hydro Man":HydroMan, "Hydroman":HydroMan, "Killmonger":Killmonger, "MBaku":MBaku, "Mbaku":MBaku, "M'baku":MBaku, "Bobbi Morse":Mockingbird, "Richard Rider":RichardRider, "Phyla Vell":PhylaVell, "Red She Hulk":RedSheHulk, "Klaue":UlyssesKlaue, "Ant Man":AntMan}

leaders = []
supports = []

t4s = [Odin, AdamWarlock, AntMan, BlackBolt, BlackWidow, BlueDragon, CaptainAmerica, SharonRogers, Carnage, DoctorOctopus, Gamora, Hulk, LunaSnow, IronMan, JeanGrey, Magneto, MoonKnight, Namor, ProfessorX, ShadowShell, SpiderGwen, SpiderMan, MilesMorales, StarLord, Storm, Thanos, Thor, Venom, Wolverine, CaptainMarvel, Loki, BlackPanther, Cable, DoctorStrange, GhostRider, BetaRayBill, Cyclops, Gladiator, Hela, MadelynePryor, Mystique, Rogue, SilverSurfer, EbonyMaw, Echo, Angel, Sentry, MrFantastic, InvisibleWoman, HumanTorch, ScarletWitch, Quicksilver, DoctorDoom, Psylocke, Deadpool, Nicepool, Gwenpool, x23, Hulkbuster, WarMachine, Apocalypse, Wong, WeaponHex]

t3s = [CassandraNova, BlackSwan, Hellstorm, Satana, Enchantress, Malekith, Ulik, Angela, Kang, Mysterio, Sylvie, NickFury, Korath, MinnErva, MsMarvel, Spectrum, AncientOne, Blade, BlueMarvel, Crescent, Daredevil, Dormammu, Elektra, EmmaFrost, Falcon, Gorr, GreenGoblin, Groot, Havok, Hawkeye, Hyperion, Iceman, Ikaris, Kingpin, KittyPryde, Knull, Modok, Magik, Mephisto, MoleculeMan, MorganLeFay, OmegaRed, PhilCoulson, Polaris, ProximaMidnight, Punisher, RocketRaccoon, Ronan, Sabretooth, ScarletSpider, ShangChi, SheHulk, Shuri, Sin, SisterGrimm, SpiderMan2099, SquirrelGirl, Stryfe, Taskmaster, Thena, JaneFoster, Ultron, Vision, Wenwu, WhiteFox, WinterSoldier, AbsorbingMan, Aero, AgentVenom, AmericaChavez, Arachknight, Ares, BaronMordo, Beast, Bishop, BlackDwarf, Bullseye, Clea, Colossus, CorvusGlaive, Destroyer, DoctorVoodoo, Domino, Drax, Electro, ElsaBloodstone, Gambit, GhostPanther, RobbieReyes, GiantMan, Gilgamesh, KateBishop, Heimdall, HopeSummers, AmadeusCho, Ikon, IronFist, IronHammer, Ironheart, JessicaJones, Juggernaut, Kaecilius, Kahhori, Katy, KidOmega, Kingo, Kraven, LincolnCampbell, Lizard, LukeCage, Makkari, ManThing, Mantis, Medusa, MisterSinister, MoonGirl, Moonstone, Morbius, Nebula, Nightcrawler, SamAlexander, AvrilKincaid, WendellVaughn, RachelSummers, RedGuardian, RedSkull, Rescue, Rhino, Sandman, Scorpion, Scream, Sersi, Sif, Silk, Skurge, SpiderWoman, Spot, SunBird, Supergiant, SwordMaster, Thing, Titania, Toxin, Valkyrie, Vulture, WarTiger, Warpath, Wasp, NadiaVanDyne, Wave, YelenaBelova, Thane, AntiMan, Fandral, Volstagg, Hogun, FranklinRichards, ValeriaRichards, Victorius, Yondu, Dazzler, Jubilee, Negasonic, Daken, Hulkling, Wiccan, Okoye, Killmonger, MBaku, Abomination]

t2s = [Agent13, Zemo, BlackCat, CassieLang, Crossbones, Crystal, Quake, Darkhawk, Deathlok, Exodus, Fantomex, Ghost, Goliath, Gorgon, GorillaMan, Hellcat, HydroMan, Inferno, Karnak, KidKaiju, Lash, Maximus, MistyKnight, Mockingbird, MoltenMan, RichardRider, PhylaVell, RedHulk, RedSheHulk, Sentinel, Singularity, Slapstick, Songbird, UlyssesKlaue, Viper, Warwolf, Whiplash, WhiteTiger, Yellowjacket]
